# Site settings
title: Vinicius Yaunner
email: vinifysantos@gmail.com
description: Programmer and Arch Linux user.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: SP
zip_code: 
country: Brazil
phone: 

icon:  # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url: https://github.com/viniciusyaunner
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/viniciusyaunner/
linkedin_url: https://www.linkedin.com/in/viniciusyaunner/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown

sass:
style: compressed
